package com.testing.pdev.model;

// Generated Apr 12, 2016 12:45:38 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */

@NamedNativeQueries({
	@NamedNativeQuery(
	name = "findEmployeeByDiffParam",
	query = "select * from employee WHERE Match ( `Emp_Name`, `Empl_Type` , `Dept_ID`, `Manager_Name`, `Recruiter` , "
			+ "`Functions`, `Location` , `Customer` , `Client_Name` , `Industry`  ,  `Home_City` , `Home_State`,  `WorkSite_City` , `WorkSite_State` , `Tax_location` ) "
			+ "AGAINST (?1 IN BOOLEAN MODE);",
        resultClass = Employee.class
	)
})

@Entity
@Table(name = "employee", catalog = "tutorials")
public class Employee implements java.io.Serializable {

	private int empId;
	private String emplRecord;
	private String empStatus;
	private String empName;
	private String emplType;
	private String deptId;
	private String managerId;
	private String managerName;
	private String aeId;
	private String accountExecutive;
	private String recruiterId;
	private String recruiter;
	private String functions;
	private String title;
	private String locationCode;
	private String location;
	private String customerId;
	private String customer;
	private String clientId;
	private String clientName;
	private String verticalId;
	private String vertical;
	private String industry;
	private String productId;
	private String product;
	private String homeAddress;
	private String homeAddress1;
	private String homeAddress2;
	private String homeAddress3;
	private String homeAddress4;
	private String homeCity;
	private String homeState;
	private String homePostal;
	private String workSiteAddress;
	private String workSiteAddress1;
	private String workSiteAddress2;
	private String workSiteCity;
	private String workSiteState;
	private String workSitePostal;
	private String phone;
	private String email;
	private String taxLocation;

	@Override
	public String toString() {
		return "Employee [empId=" + empId + ", emplRecord=" + emplRecord
				+ ", empStatus=" + empStatus + ", empName=" + empName
				+ ", emplType=" + emplType + ", deptId=" + deptId
				+ ", managerId=" + managerId + ", managerName=" + managerName
				+ ", aeId=" + aeId + ", accountExecutive=" + accountExecutive
				+ ", recruiterId=" + recruiterId + ", recruiter=" + recruiter
				+ ", functions=" + functions + ", title=" + title
				+ ", locationCode=" + locationCode + ", location=" + location
				+ ", customerId=" + customerId + ", customer=" + customer
				+ ", clientId=" + clientId + ", clientName=" + clientName
				+ ", verticalId=" + verticalId + ", vertical=" + vertical
				+ ", industry=" + industry + ", productId=" + productId
				+ ", product=" + product + ", homeAddress=" + homeAddress
				+ ", homeAddress1=" + homeAddress1 + ", homeAddress2="
				+ homeAddress2 + ", homeAddress3=" + homeAddress3
				+ ", homeAddress4=" + homeAddress4 + ", homeCity=" + homeCity
				+ ", homeState=" + homeState + ", homePostal=" + homePostal
				+ ", workSiteAddress=" + workSiteAddress
				+ ", workSiteAddress1=" + workSiteAddress1
				+ ", workSiteAddress2=" + workSiteAddress2 + ", workSiteCity="
				+ workSiteCity + ", workSiteState=" + workSiteState
				+ ", workSitePostal=" + workSitePostal + ", phone=" + phone
				+ ", email=" + email + ", taxLocation=" + taxLocation + "]";
	}

	public Employee() {
	}

	public Employee(int empId) {
		this.empId = empId;
	}

	public Employee(int empId, String emplRecord, String empStatus,
			String empName, String emplType, String deptId, String managerId,
			String managerName, String aeId, String accountExecutive,
			String recruiterId, String recruiter, String functions,
			String title, String locationCode, String location,
			String customerId, String customer, String clientId,
			String clientName, String verticalId, String vertical,
			String industry, String productId, String product,
			String homeAddress, String homeAddress1, String homeAddress2,
			String homeAddress3, String homeAddress4, String homeCity,
			String homeState, String homePostal, String workSiteAddress,
			String workSiteAddress1, String workSiteAddress2,
			String workSiteCity, String workSiteState, String workSitePostal,
			String phone, String email, String taxLocation) {
		this.empId = empId;
		this.emplRecord = emplRecord;
		this.empStatus = empStatus;
		this.empName = empName;
		this.emplType = emplType;
		this.deptId = deptId;
		this.managerId = managerId;
		this.managerName = managerName;
		this.aeId = aeId;
		this.accountExecutive = accountExecutive;
		this.recruiterId = recruiterId;
		this.recruiter = recruiter;
		this.functions = functions;
		this.title = title;
		this.locationCode = locationCode;
		this.location = location;
		this.customerId = customerId;
		this.customer = customer;
		this.clientId = clientId;
		this.clientName = clientName;
		this.verticalId = verticalId;
		this.vertical = vertical;
		this.industry = industry;
		this.productId = productId;
		this.product = product;
		this.homeAddress = homeAddress;
		this.homeAddress1 = homeAddress1;
		this.homeAddress2 = homeAddress2;
		this.homeAddress3 = homeAddress3;
		this.homeAddress4 = homeAddress4;
		this.homeCity = homeCity;
		this.homeState = homeState;
		this.homePostal = homePostal;
		this.workSiteAddress = workSiteAddress;
		this.workSiteAddress1 = workSiteAddress1;
		this.workSiteAddress2 = workSiteAddress2;
		this.workSiteCity = workSiteCity;
		this.workSiteState = workSiteState;
		this.workSitePostal = workSitePostal;
		this.phone = phone;
		this.email = email;
		this.taxLocation = taxLocation;
	}

	@Id
	@Column(name = "Emp_ID", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "Empl_Record", length = 36)
	public String getEmplRecord() {
		return this.emplRecord;
	}

	public void setEmplRecord(String emplRecord) {
		this.emplRecord = emplRecord;
	}

	@Column(name = "EMP_Status", length = 36)
	public String getEmpStatus() {
		return this.empStatus;
	}

	public void setEmpStatus(String empStatus) {
		this.empStatus = empStatus;
	}

	@Column(name = "Emp_Name", length = 36)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "Empl_Type", length = 36)
	public String getEmplType() {
		return this.emplType;
	}

	public void setEmplType(String emplType) {
		this.emplType = emplType;
	}

	@Column(name = "Dept_ID", length = 36)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "Manager_ID", length = 36)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "Manager_Name", length = 36)
	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	@Column(name = "AE_ID", length = 36)
	public String getAeId() {
		return this.aeId;
	}

	public void setAeId(String aeId) {
		this.aeId = aeId;
	}

	@Column(name = "Account_Executive", length = 36)
	public String getAccountExecutive() {
		return this.accountExecutive;
	}

	public void setAccountExecutive(String accountExecutive) {
		this.accountExecutive = accountExecutive;
	}

	@Column(name = "Recruiter_ID", length = 36)
	public String getRecruiterId() {
		return this.recruiterId;
	}

	public void setRecruiterId(String recruiterId) {
		this.recruiterId = recruiterId;
	}

	@Column(name = "Recruiter", length = 36)
	public String getRecruiter() {
		return this.recruiter;
	}

	public void setRecruiter(String recruiter) {
		this.recruiter = recruiter;
	}

	@Column(name = "Functions", length = 36)
	public String getFunctions() {
		return this.functions;
	}

	public void setFunctions(String functions) {
		this.functions = functions;
	}

	@Column(name = "Title", length = 36)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Location_Code", length = 36)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	@Column(name = "Location", length = 36)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "Customer_ID", length = 36)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "Customer", length = 36)
	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	@Column(name = "Client_ID", length = 36)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "Client_Name", length = 36)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "Vertical_ID", length = 36)
	public String getVerticalId() {
		return this.verticalId;
	}

	public void setVerticalId(String verticalId) {
		this.verticalId = verticalId;
	}

	@Column(name = "Vertical", length = 36)
	public String getVertical() {
		return this.vertical;
	}

	public void setVertical(String vertical) {
		this.vertical = vertical;
	}

	@Column(name = "Industry", length = 36)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "Product_ID", length = 36)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "Product", length = 36)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "Home_Address", length = 72)
	public String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Column(name = "Home_Address_1", length = 72)
	public String getHomeAddress1() {
		return this.homeAddress1;
	}

	public void setHomeAddress1(String homeAddress1) {
		this.homeAddress1 = homeAddress1;
	}

	@Column(name = "Home_Address_2", length = 72)
	public String getHomeAddress2() {
		return this.homeAddress2;
	}

	public void setHomeAddress2(String homeAddress2) {
		this.homeAddress2 = homeAddress2;
	}

	@Column(name = "Home_Address_3", length = 36)
	public String getHomeAddress3() {
		return this.homeAddress3;
	}

	public void setHomeAddress3(String homeAddress3) {
		this.homeAddress3 = homeAddress3;
	}

	@Column(name = "Home_Address_4", length = 36)
	public String getHomeAddress4() {
		return this.homeAddress4;
	}

	public void setHomeAddress4(String homeAddress4) {
		this.homeAddress4 = homeAddress4;
	}

	@Column(name = "Home_City", length = 36)
	public String getHomeCity() {
		return this.homeCity;
	}

	public void setHomeCity(String homeCity) {
		this.homeCity = homeCity;
	}

	@Column(name = "Home_State", length = 36)
	public String getHomeState() {
		return this.homeState;
	}

	public void setHomeState(String homeState) {
		this.homeState = homeState;
	}

	@Column(name = "Home_Postal", length = 36)
	public String getHomePostal() {
		return this.homePostal;
	}

	public void setHomePostal(String homePostal) {
		this.homePostal = homePostal;
	}

	@Column(name = "WorkSite_Address", length = 72)
	public String getWorkSiteAddress() {
		return this.workSiteAddress;
	}

	public void setWorkSiteAddress(String workSiteAddress) {
		this.workSiteAddress = workSiteAddress;
	}

	@Column(name = "WorkSite_Address_1", length = 72)
	public String getWorkSiteAddress1() {
		return this.workSiteAddress1;
	}

	public void setWorkSiteAddress1(String workSiteAddress1) {
		this.workSiteAddress1 = workSiteAddress1;
	}

	@Column(name = "WorkSite_Address_2", length = 72)
	public String getWorkSiteAddress2() {
		return this.workSiteAddress2;
	}

	public void setWorkSiteAddress2(String workSiteAddress2) {
		this.workSiteAddress2 = workSiteAddress2;
	}

	@Column(name = "WorkSite_City", length = 36)
	public String getWorkSiteCity() {
		return this.workSiteCity;
	}

	public void setWorkSiteCity(String workSiteCity) {
		this.workSiteCity = workSiteCity;
	}

	@Column(name = "WorkSite_State", length = 36)
	public String getWorkSiteState() {
		return this.workSiteState;
	}

	public void setWorkSiteState(String workSiteState) {
		this.workSiteState = workSiteState;
	}

	@Column(name = "WorkSite_Postal", length = 36)
	public String getWorkSitePostal() {
		return this.workSitePostal;
	}

	public void setWorkSitePostal(String workSitePostal) {
		this.workSitePostal = workSitePostal;
	}

	@Column(name = "Phone", length = 36)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Email", length = 48)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Tax_location", length = 36)
	public String getTaxLocation() {
		return this.taxLocation;
	}

	public void setTaxLocation(String taxLocation) {
		this.taxLocation = taxLocation;
	}

}
